### ISSUE TITLE
Upgrade tests

### ISSUE THREAD

**Issue by JohnKhandygo** [angdust/transpose#5]
- [ ] Я как-то совсем упустил из виду. Ваши тесты в принципе ничего не проверяют. Совсем.

**Comment by angdust** [comment]
Так давайте еще раз...

> 

Во-первых, Ваши тесты ничего не проверяют. Это самое главное...
--
> 

Исправил замечания от беглого просмотра.Почему мои тесты ничего не проверяют?Что конкретно мне лучше сделать?
--

> 

С тестами уже все хорошо, не переживайте.
--





--

**Comment by JohnKhandygo** [comment]
Да, так лучше. Только я не понял, зачем Вы везде эти `try ... catch` понапихали.
